TCC/Models/Mesa.cs
using MySql.Data.MySqlClient;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace TCC.Models
{
    public class Mesa
    {
        private ConexaoDB db;

        [Required(ErrorMessage = "O campo Número da mesa é requerido.")]
        [Display(Name = "Número da mesa")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Digite somente números.")]
        [Range(0, int.MaxValue, ErrorMessage = "Deve ser positivo")]
        public int IdMesa { get; set; }

        [Required(ErrorMessage = "O campo Numero de lugares é requerido.")]
        [Display(Name = "Numero de lugares")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Digite somente números.")]
        [Range(0, int.MaxValue, ErrorMessage = "Deve ser positivo")]
        public int Numlugares { get; set; }

        [Required(ErrorMessage = "O campo Disponivel é requerido.")]
        [Display(Name = "Disponivel")]
        public bool Disponi { get; set; }

        [Display(Name = "Tipo de lugar")]
        [RegularExpression(@"^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ'\s]+$", ErrorMessage = "Digite somente letras.")]
        [StringLength(50, ErrorMessage = "A quantidade de caracteres do Tipo de lugar é invalido.")]
        public string TipoLugar { get; set; }


        public string Imagem { get; set; }

        public HttpPostedFileBase ImageUpload { get; set; }

        public void InsertMesa(Mesa mesa)
        {
            string strQuery = string.Format("call sp_InsMesa('{0}','{1}','{2}');",mesa.Imagem,mesa.Numlugares,mesa.TipoLugar);

            using (db = new ConexaoDB())
            {
                db.ExecutaComando(strQuery);
            }
        }

        public List<Mesa> SelecionaMesa()
        {
            using (db = new ConexaoDB())
            {
                string StrQuery = string.Format("select * from tbmesa;");
                MySqlDataReader registros = db.RetornaRegistro(StrQuery);
                var mesaList = new List<Mesa>();
                while (registros.Read())
                {
                    var MesaTemporaria = new Mesa
                    {
                        IdMesa = int.Parse(registros["IdMesa"].ToString()),
                        Numlugares = int.Parse(registros["Numlugares"].ToString()),
                        Disponi = bool.Parse(registros["Disponi"].ToString()),
                        TipoLugar = registros["TipoLugar"].ToString(),
                        Imagem =  registros["imagemesa"].ToString()
                    };
                    mesaList.Add(MesaTemporaria);
                }
                return mesaList;
            }
        }

        public Mesa SelecionaIdMesa(int IdMesa)
        {
            using (db = new ConexaoDB())
            {
                string StrQuery = string.Format("select * from tbmesa where IdMesa = '{0}';", IdMesa);
                MySqlDataReader registros = db.RetornaRegistro(StrQuery);
                Mesa mesaListando = null;
                while (registros.Read())
                {
                    mesaListando = new Mesa
                    {
                        IdMesa = int.Parse(registros["IdMesa"].ToString()),
                        Numlugares = int.Parse(registros["Numlugares"].ToString()),
                        Disponi = bool.Parse(registros["Disponi"].ToString()),
                        TipoLugar = registros["TipoLugar"].ToString(),
                        Imagem = registros["imagemesa"].ToString()
                    };
                }

                return mesaListando;
            }

        }



    }
}

TCC/Controllers/MesaController.cs
using System;
using System.IO;
using System.Web.Mvc;
using TCC.Autorizacoes;
using TCC.Models;

namespace TCC.Controllers
{

    public class MesaController : Controller
    {

        // GET: Mesa
        public ActionResult Index()
        {
            return View();
        }

        // GET: Mesa/Details/5
        public ActionResult Details(int IdMesa)
        {
            try
            {
                var mesa = new Mesa();
                var objMesa = new Mesa();
                mesa = objMesa.SelecionaIdMesa(IdMesa);
                return View(mesa);
            }
            catch
            {
                TempData["msg"] = "<script>alert('Erro ao detalhar a mesa');</script>";
                return View();
            }
        }

        [Autenticacao]
        public ActionResult List(Mesa mesa)
        {
            try
            {
                if (int.Parse(Session["NivelAcesso"].ToString()) != 1 && int.Parse(Session["NivelAcesso"].ToString()) != 5 && int.Parse(Session["NivelAcesso"].ToString()) != 2)
                {
                    return RedirectToAction("ErroAutenticação", "Usuario");
                }
                var mesaList = mesa.SelecionaMesa();
                return View(mesaList);
            }
            catch
            {
                TempData["msg"] = "<script>alert('Erro ao listar as mesas');</script>";
                return View();
            }
        }

        // GET: Mesa/Create
        [Autenticacao]
        public ActionResult Create()
        {

            if (int.Parse(Session["NivelAcesso"].ToString()) != 5)
            {
                return RedirectToAction("ErroAutenticação", "Usuario");
            }

            var objMesa = new Mesa();
            int[] NumLugar = new int[] { 1, 2, 3, 4, 5 }; //5, pois é o maximo de cadeiras que uma mesa pode ter
            SelectList Lista = new SelectList(NumLugar);
            ViewBag.Lista = Lista;

            string[] TipoLugar = new string[] { "Coberto", "Arejado" };
            SelectList ListaTipoLugar = new SelectList(TipoLugar);
            ViewBag.ListaTipoLugar = ListaTipoLugar;

            return View(objMesa);
        }

        // POST: Mesa/Create
        [HttpPost]
        public ActionResult Create(Mesa mesa)
        {
            if (ModelState.IsValid)
            {
                var objMesa = new Mesa();
                string filename = Path.GetFileNameWithoutExtension(mesa.ImageUpload.FileName);
                string extesion = Path.GetExtension(mesa.ImageUpload.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + extesion;
                mesa.Imagem = "~/Imagens/" + filename;
                filename = Path.Combine(Server.MapPath("~/Imagens/"), filename);
                mesa.ImageUpload.SaveAs(filename);
                objMesa.InsertMesa(mesa);
                return RedirectToAction("BemvindoADM", "Home");
            }
            TempData["msg"] = "<script>alert('Erro ao criar a mesa');</script>";
            return View();
        }     
    }
}

TCC/Views/Mesa/Create.cshtml
@*@model TCC.Models.Mesa

    @{
        ViewBag.Title = "Create";
    }

    <h2>Create</h2>

    @using (Html.BeginForm("Create", "Mesa", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Mesa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
                @Html.LabelFor(model => model.Numlugares, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Numlugares, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Numlugares, "", new { @class = "text-danger" })
                </div>
            </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Numlugares, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Numlugares, ViewBag.Lista as SelectList, "Selecione o número de cadeiras", htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
                @Html.LabelFor(model => model.Disponi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Disponi)
                        @Html.ValidationMessageFor(model => model.Disponi, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoLugar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoLugar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoLugar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Imagem, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageUpload" required />
                @Html.ValidationMessageFor(m => m.Imagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
    @Html.Raw(TempData["msg"])
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@


@model TCC.Models.Mesa

@{
    ViewBag.Title = "Create";
}
<link rel="stylesheet" type="text/css" href="~/CSS/form.css">
<h1 class="formTitle">Mesa</h1>
@using (Html.BeginForm("Create", "Mesa", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @*<div class="form-group">
            @Html.LabelFor(model => model.Numlugares, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numlugares, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numlugares, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="wrapper">
        <section class="dropDown-Data">
            @Html.DropDownListFor(model => model.Numlugares, ViewBag.Lista as SelectList, "Selecione o número de cadeiras", new { @class = "dropdown" })
            <section class="line"></section>
        </section>
        @Html.ValidationMessageFor(model => model.Numlugares, "", new { @class = "text-danger" })
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Disponi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Disponi)
                    @Html.ValidationMessageFor(model => model.Disponi, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

    <div class="wrapper">
        <section class="dropDown-Data">
            @Html.DropDownListFor(model => model.TipoLugar, ViewBag.ListaTipoLugar as SelectList, "Selecione um tipo de lugar", new { @class = "dropdown" })
            <section class="line"></section>
        </section>
        @Html.ValidationMessageFor(model => model.TipoLugar, "", new { @class = "text-danger" })
    </div>

    <div class="wrapper">
        <section class="input-Data">
            @Html.LabelFor(m => m.Imagem, new { @class = "imgOptionForm" })
            <div class="col-md-10">
                <input type="file" name="ImageUpload" required />
                @*@Html.ValidationMessageFor(m => m.Imagem, "", new { @class = "text-danger" })*@
            </div>
        </section>
    </div>

    <div class="bottomForm">
        <section class="bottomFormBottom">
            <button type="submit" id="submit">Criar Mesa</button>
        </section>
    </div>
}
@Html.Raw(TempData["msg"])

TCC/Views/Mesa/Details.cshtml
@model TCC.Models.Mesa

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Mesa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdMesa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdMesa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numlugares)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numlugares)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Disponi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Disponi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoLugar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoLugar)
        </dd>

    </dl>
</div>
@Html.Raw(TempData["msg"])
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TCC/Views/Mesa/Edit.cshtml
@model TCC.Models.Mesa

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Mesa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdMesa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdMesa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdMesa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@Html.Raw(TempData["msg"])
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TCC/Views/Mesa/List.cshtml
@model IEnumerable<TCC.Models.Mesa>

@{
    ViewBag.Title = "List";
}

<link rel="stylesheet" type="text/css" href="~/CSS/List.css">
<section class="contenteTable">
    <h2 class="tableTitle">Lista de Clientes Cadastrados</h2>
    <div>
        <table class="table ">
            <tr class="colorTable">
                <th>
                    @Html.DisplayNameFor(model => model.IdMesa)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Numlugares)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Disponi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TipoLugar)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Imagem)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdMesa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Numlugares)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Disponi)
                    </td>
                    <td>
                        @if (!string.IsNullOrEmpty(item.Imagem))
                        {
                            <img src="@Url.Content(item.Imagem)" alt="Sem imagem" style="width:100px;height:100px;max-width:100%;height:auto" />
                        }
                    </td>
                    <td>
                        @Html.ActionLink(" ", "Edit", new { IdMesa = item.IdMesa }, new { @Class = "fas fa-sync" })
                    </td>
                    <td>
                        @Html.ActionLink(" ", "Delete", new { IdMesa = item.IdMesa }, new { @Class = "fas fa-eraser" })
                    </td>
                </tr>
            }
            @Html.Raw(TempData["msg"])
        </table>
    </div>
</section>