TCC/Models/Produto.cs
using MySql.Data.MySqlClient;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace TCC.Models
{
    public class Produto
    {
        private ConexaoDB db;

        [Required(ErrorMessage = "O campo Id do produto é requerido.")]
        [Display(Name = "Id do produto")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Digite somente números.")]
        [Range(0, int.MaxValue, ErrorMessage = "Deve ser positivo")]
        public int IdProd { get; set; }
        
        [Required(ErrorMessage = "O campo Nome do produto é requerido.")]
        [StringLength(200,ErrorMessage = "A quantidade de caracteres do Nome do produto é invalido.")]
        [Display(Name = "Nome do produto")]
        [RegularExpression(@"^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ'\s]+$", ErrorMessage = "Digite somente letras.")]
        public string NomeProd { get; set; }

        [Required(ErrorMessage = "O campo Valor do produto é requerido.")]
        [Display(Name = "Valor do produto")]
        [DisplayFormat(DataFormatString = "{0:C2}", ApplyFormatInEditMode = true)]
        public float ValorProd { get; set; }

        [Required(ErrorMessage = "O campo Descrição do produto é requerido.")]
        [Display(Name = "Descrição do produto")]
        [RegularExpression(@"^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ'\s]+$", ErrorMessage = "Digite somente letras.")]
        [StringLength(200, ErrorMessage = "A quantidade de caracteres da Descrição do produto é invalido.")]
        public string DescProd { get; set; }

        [RegularExpression(@"^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ'\s]+$", ErrorMessage = "Digite somente letras.")]
        [Display(Name = "Observação do produto")]
        [StringLength(200, ErrorMessage = "A quantidade de caracteres da Observação do produto é invalido.")]
        public string Observacao { get; set; }

        [Display(Name = "Tipo de produto")]
        [StringLength(50, ErrorMessage = "A quantidade de caracteres do Tipo de produto é invalido.")]
        public string TipoProd { get; set; }

        [Display(Name = "Categoria do produto")]
        [StringLength(50, ErrorMessage = "A quantidade de caracteres da Categoria do produto é invalido.")]
        public string CategoriaProd { get; set; }

        public int Qtd { get; set; }



        public string Imagem { get; set; }

        public HttpPostedFileBase ImageUpload { get; set; }

        public void InsertProduto(Produto produto)
        {
            string strQuery = string.Format("CALL sp_InsProd('{0}','{1}','{2}','{3}','{4}','{5}','{6}');", produto.Imagem,produto.NomeProd, produto.DescProd, produto.Observacao, produto.ValorProd.ToString().Replace(",", "."), produto.TipoProd, produto.CategoriaProd);

            using (db = new ConexaoDB())
            {
                db.ExecutaComando(strQuery);
            }
        }

        public void UpdateProduto(Produto produto)
        {
            string strQuery = string.Format("CALL sp_AtuaProd('{0}','{1}','{2}','{3}','{4}','{5}','{6}');", produto.IdProd, produto.NomeProd, produto.DescProd, produto.Observacao, produto.ValorProd.ToString().Replace(",", "."), produto.TipoProd, produto.CategoriaProd);

            using (db = new ConexaoDB())
            {
                db.ExecutaComando(strQuery);
            }
        }

        public List<Produto> SelecionaProduto()
        {
            using (db = new ConexaoDB())
            {
                string StrQuery = string.Format("select * from tbproduto;");
                MySqlDataReader registros = db.RetornaRegistro(StrQuery);
                var produtoList = new List<Produto>();
                while (registros.Read())
                {
                    string obs = registros["Observacao"].ToString();
                    var ProdutoTemporaria = new Produto
                    {
                        IdProd = int.Parse(registros["IdProd"].ToString()),
                        NomeProd = registros["NomeProd"].ToString(),
                        DescProd = registros["DescProd"].ToString(),
                        ValorProd = float.Parse(registros["ValorProd"].ToString()),
                        Observacao = obs.Equals("") ? "Sem observação" : registros["Observacao"].ToString(),
                        TipoProd = registros["TipoProd"].ToString(),
                        CategoriaProd = registros["CategoriaProd"].ToString(),
                        Imagem = registros["imageprod"].ToString()
                    };
                    produtoList.Add(ProdutoTemporaria);
                }
                return produtoList;
            }
        }

        public Produto SelecionaIdProd(int IdProd)
        {
            using (db = new ConexaoDB())
            {
                string StrQuery = string.Format("select * from tbproduto where IdProd = '{0}';", IdProd);
                MySqlDataReader registros = db.RetornaRegistro(StrQuery);
                Produto ProdutoListando = null;
                while (registros.Read())
                {
                    string obs = registros["Observacao"].ToString();
                     ProdutoListando = new Produto
                    {
                        IdProd = int.Parse(registros["IdProd"].ToString()),
                        NomeProd = registros["NomeProd"].ToString(),
                        DescProd = registros["DescProd"].ToString(),
                        ValorProd = float.Parse(registros["ValorProd"].ToString()),
                        Observacao = obs.Equals("") ? "Sem observação" : registros["Observacao"].ToString(),
                        TipoProd = registros["TipoProd"].ToString(),
                        CategoriaProd = registros["CategoriaProd"].ToString(),
                        Imagem = registros["imageprod"].ToString()
                    };
                }

                return ProdutoListando;
            }

        }

        public List<Produto> SelecionaIdProdCart(int IdProd)
        {
            using (db = new ConexaoDB())
            {
                string StrQuery = string.Format("select * from tbproduto where IdProd = '{0}';", IdProd);
                MySqlDataReader registros = db.RetornaRegistro(StrQuery);
                var produtoList = new List<Produto>();
                while (registros.Read())
                {
                    string obs = registros["Observacao"].ToString();
                    Produto ProdutoListando = new Produto
                    {
                        IdProd = int.Parse(registros["IdProd"].ToString()),
                        NomeProd = registros["NomeProd"].ToString(),
                        DescProd = registros["DescProd"].ToString(),
                        ValorProd = float.Parse(registros["ValorProd"].ToString()),
                        Observacao = obs.Equals("") ? "Sem observação" : registros["Observacao"].ToString(),
                        TipoProd = registros["TipoProd"].ToString(),
                        CategoriaProd = registros["CategoriaProd"].ToString(),
                        Imagem = registros["imageprod"].ToString()
                    };
                    produtoList.Add(ProdutoListando);
                }

                return produtoList;
            }

        }

        public Produto SelecionaComIdProd(int IdProd)
        {
            using (db = new ConexaoDB())
            {
                string StrQuery = string.Format("select IdProd from tbproduto where IdProd = '{0}';", IdProd);
                MySqlDataReader registros = db.RetornaRegistro(StrQuery);
                Produto comandaListando = null;
                while (registros.Read())
                {
                    comandaListando = new Produto
                    {
                        IdProd = int.Parse(registros["IdProd"].ToString()),
                    };
                }

                return comandaListando;
            }

        }

        public List<Produto> BuscaProduto(string busca)
        {
            using (db = new ConexaoDB())
            {
                string StrQuery = string.Format("CALL sp_Like('{0}');",busca);
                MySqlDataReader registros = db.RetornaRegistro(StrQuery);
                var produtoList = new List<Produto>();
                while (registros.Read())
                {
                    string obs = registros["Observacao"].ToString();
                    var ProdutoTemporaria = new Produto
                    {
                        IdProd = int.Parse(registros["IdProd"].ToString()),
                        NomeProd = registros["NomeProd"].ToString(),
                        DescProd = registros["DescProd"].ToString(),
                        ValorProd = float.Parse(registros["ValorProd"].ToString()),
                        Observacao = obs.Equals("") ? "Sem observação" : registros["Observacao"].ToString(),
                        TipoProd = registros["TipoProd"].ToString(),
                        CategoriaProd = registros["CategoriaProd"].ToString(),
                        Imagem = registros["imageprod"].ToString()
                    };

                    produtoList.Add(ProdutoTemporaria);
                }
                return produtoList;
            }
        }




    }
}

TCC/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using TCC.Autorizacoes;
using TCC.Models;

namespace TCC.Controllers
{
    public class ProdutoController : Controller
    {
        // GET: Produto
        public ActionResult Index()
        {
            return View();
        }

        // GET: Produto/Details/5
        [Autenticacao]
        public ActionResult Details(int IdProd)
        {
            try
            {
                var produto = new List<Produto>();
                var objProduto = new Produto();
                produto = objProduto.SelecionaIdProdCart(IdProd);
                return View(produto);
            }
            catch
            {
                TempData["msg"] = "<script>alert('Erro ao detalhar o produto');</script>";
                return View();
            }
        }

        [Autenticacao]
        public ActionResult List(Produto produto,string busca)
        {
            try
            {
                var prodBusca = produto.BuscaProduto(busca);
                if(prodBusca.Count == 0) 
                { 
                    TempData["msgSemDado"] = "<script>alert('Nenhum produto encontrado');</script>"; 
                    return View(prodBusca);
                };
                return View(prodBusca);
            }
            catch
            {
                TempData["msg"] = "<script>alert('Erro ao listar os produtos');</script>";
                return View();
            }
        }

        // GET: Produto/Create
        [Autenticacao]
        public ActionResult Create()
        {
            if (int.Parse(Session["NivelAcesso"].ToString()) != 5)
            {
                return RedirectToAction("ErroAutenticação", "Usuario");
            }
            return View();
        }




        // POST: Produto/Create
        [HttpPost]
        public ActionResult Create(Produto produto)
        {

            if (ModelState.IsValid)
            {
                var objProduto = new Produto();
                string filename = Path.GetFileNameWithoutExtension(produto.ImageUpload.FileName);
                string extesion = Path.GetExtension(produto.ImageUpload.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + extesion;
                produto.Imagem = "/Imagens/" + filename;
                filename = Path.Combine(Server.MapPath("/Imagens/"), filename);
                produto.ImageUpload.SaveAs(filename);
                objProduto.InsertProduto(produto);
                return RedirectToAction("BemvindoADM", "Home");
            }
            TempData["msg"] = "<script>alert('Erro ao criar o produto');</script>";
            return View();
        }

        // GET: Produto/Edit/5
        [Autenticacao]
        public ActionResult Edit(int IdProd)
        {
            if (int.Parse(Session["NivelAcesso"].ToString()) != 5)
            {
                return RedirectToAction("ErroAutenticação", "Usuario");
            }
            var produto = new Produto();
            var objProduto = new Produto();
            produto = objProduto.SelecionaIdProd(IdProd);
            return View(produto);
        }

        // POST: Produto/Edit/5
        [HttpPost]
        public ActionResult Edit(Produto produto)
        {
            try
            {
                var objProduto = new Produto();
                objProduto.UpdateProduto(produto);
                return RedirectToAction("List");
            }
            catch
            {
                TempData["msg"] = "<script>alert('Erro ao editar o produto');</script>";
                return View();
            }
        
        }
    }
}

TCC/Views/Produto/Create.cshtml
@model TCC.Models.Produto

@{
    ViewBag.Title = "Create";
}

<link rel="stylesheet" type="text/css" href="~/CSS/form.css">
<h1 class="formTitle">Cadastro de Produtos</h1>
@using (Html.BeginForm("Create", "Produto", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="wrapper">
        <section class="input-Data">
            @Html.EditorFor(model => model.NomeProd)
            <section class="line"></section>
            @Html.LabelFor(model => model.NomeProd)
        </section>
        @Html.ValidationMessageFor(model => model.NomeProd, "", new { @class = "text-danger" })
    </div>

    <div class="wrapper">
        <section class="input-Data">
            @Html.EditorFor(model => model.ValorProd)
            <section class="line"></section>
            @Html.LabelFor(model => model.ValorProd)
        </section>
        @Html.ValidationMessageFor(model => model.ValorProd, "", new { @class = "text-danger" })
    </div>
    <div class="wrapper">
        <section class="input-Data">
            @Html.EditorFor(model => model.DescProd)
            <section class="line"></section>
            @Html.LabelFor(model => model.DescProd)
        </section>
        @Html.ValidationMessageFor(model => model.DescProd, "", new { @class = "text-danger" })
    </div>

    <div class="wrapper">
        <section class="input-Data">
            @Html.EditorFor(model => model.Observacao)
            <section class="line"></section>
            @Html.LabelFor(model => model.Observacao)
        </section>
        @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
    </div>

    <div class="wrapper">
        <section class="input-Data">
            @Html.EditorFor(model => model.TipoProd)
            <section class="line"></section>
            @Html.LabelFor(model => model.TipoProd)
        </section>
        @Html.ValidationMessageFor(model => model.TipoProd, "", new { @class = "text-danger" })
    </div>

    <div class="wrapper">
        <section class="input-Data">
            @Html.EditorFor(model => model.CategoriaProd)
            <section class="line"></section>
            @Html.LabelFor(model => model.CategoriaProd)
        </section>
        @Html.ValidationMessageFor(model => model.CategoriaProd, "", new { @class = "text-danger" })
    </div>

    <div class="wrapper">
        <section class="input-Data">
            @Html.LabelFor(m => m.Imagem, new { @class = "imgOptionForm" })
            <input type="file" name="ImageUpload" required />
            <section class="line"></section>
        </section>
    </div>

    <div class="bottomForm">
        <section class="bottomFormBottom">
            <button type="submit" id="submit">Cadastrar</button>
        </section>
    </div>
}
@Html.Raw(TempData["msg"])
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/validations_pt-br")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
    <script src="~/Scripts/Myscript.js"></script>
}

TCC/Views/Produto/Details.cshtml
@model IEnumerable<TCC.Models.Produto>

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Cardapio.cshtml";
}

@foreach (var item in Model)
{
<div class="contentDetails">
    <section class="imgDetailsProd">

        <img src="@Url.Content(item.Imagem)" alt="FOTO">
    </section>
    <section class="infoDetailsProd">
        <h1> @Html.DisplayFor(model => item.NomeProd)</h1>
        <p class="infoDetailsProdP"> @Html.DisplayFor(model => item.DescProd)</p>
        <p>@Html.DisplayFor(model => item.ValorProd)</p>
        <section class="detailsFooter">
            @using (Html.BeginForm("AdicionaCarrinho", "Produto_pedido", new { prodId = item.IdProd, valor = item.ValorProd, nome = item.NomeProd, imagem = item.Imagem }, FormMethod.Post))
            {
                <button type="submit">Adicionar ao Carrinho</button>
                @Html.Raw(TempData["msg"])
            }
        </section>
    </section>
</div>
}

TCC/Views/Produto/Edit.cshtml
@model TCC.Models.Produto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.NomeProd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeProd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeProd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorProd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorProd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorProd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescProd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescProd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescProd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoProd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoProd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoProd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaProd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoriaProd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoriaProd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@Html.Raw(TempData["msg"])
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TCC/Views/Produto/List.cshtml
@model IEnumerable<TCC.Models.Produto>

    @{
        ViewBag.Title = "List";
        Layout = "~/Views/Shared/_Cardapio.cshtml";
    }
    <link rel="stylesheet" type="text/css" href="~/CSS/card.css">

    @using (Html.BeginForm("List", "Produto", FormMethod.Get))
    {
        <section class="searchConteiner">
            <input type="text" class="search-text" name="busca" id="busca" placeholder="Digite alguma coisa..."><button type="submit"><i class="fas fa-search" onclick="showSearch()"></i></button>
        </section>
    }

        <div class="cards">
            <section class="card">
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                <article>
                    <img src="@Url.Content(item.Imagem)" alt="Sem imagem" />
                    <section class="contentCard">
                        <h4 class="cardTitle">@Html.DisplayFor(modelItem => item.NomeProd)</h4>
                        <p class="nomeproduct"> @Html.DisplayFor(modelItem => item.DescProd)</p>
                        <p class="valorproduct">  @Html.DisplayFor(modelItem => item.ValorProd)</p>
                        <button class="searchProduct"> @Html.ActionLink("Detalhes", "Details", new { IdProd = item.IdProd })</button>
                    </section>
                </article>
                    }
                }
            </section>
        </div>
        @Html.Raw(TempData["msg"])
        @Html.Raw(TempData["msgSemDado"])