TCC/Models/Funcionario.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace TCC.Models
{
    public class Funcionario
    {

        private ConexaoDB db;

        [Required(ErrorMessage = "O campo Id do funcionário é requerido.")]
        [Display(Name = "Id do funcionário")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Digite somente números.")]
        [Range(0, int.MaxValue, ErrorMessage = "Deve ser positivo")]
        [Key]
        public int IdFunc { get; set; }

        [Required(ErrorMessage = "O campo CPF do funcionário é requerido.")]
        [Display(Name = "CPF do funcionário")]
        [StringLength(11,ErrorMessage = "A quantidade de caracteres do CPF do funcionário é invalido.",MinimumLength = 11)]
        public string CPFfunc { get; set; }

        public Endereco Endereco { get; set; }

        [Required(ErrorMessage = "O campo Nome do funcionário é requerido.")]
        [Display(Name = "Nome do funcionário")]
        [RegularExpression(@"^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ'\s]+$", ErrorMessage = "Digite somente letras.")]
        [StringLength(50, ErrorMessage = "A quantidade de caracteres do Nome do funcionário é invalido.")]
        public string NomeFunc { get; set; }

        [Required(ErrorMessage = "O campo Data de nascimento do funcionário é requerido.")]
        [Display(Name = "Data de nascimento do funcionário")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DatNascFunc { get; set; }

        [Required(ErrorMessage = "O campo Cargo do funcionário é requerido.")]
        [Display(Name = "Cargo do funcionário")]
        [RegularExpression(@"^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ'\s]+$", ErrorMessage = "Digite somente letras.")]
        [StringLength(25, ErrorMessage = "A quantidade de caracteres do Cargo do funcionário é invalido.")]
        public string CargoFunc { get; set; }

        [Required(ErrorMessage = "O campo Sexo do funcionário é requerido.")]
        [Display(Name = "Sexo do funcionário")]
        [RegularExpression(@"^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ'\s]+$", ErrorMessage = "Digite somente letras.")]
        [StringLength(1, ErrorMessage = "A quantidade de caracteres do Sexo do funcionário é invalido.")]
        public string SexoFunc { get; set; }

        [Required(ErrorMessage = "O campo Celular do funcionário é requerido.")]
        [Display(Name = "Celular do funcionário")]
        public long CelFunc { get; set; }

        [Required(ErrorMessage = "O campo Email do funcionário é requerido.")]
        [RegularExpression(@"^[-a-zA-Z0-9][-.a-zA-Z0-9]*@[-.a-zA-Z0-9]+(\.[-.a-zA-Z0-9]+)*\.(com|edu|info|gov|int|mil|net|org|biz|name|museum|coop|aero|pro|tv|[a-zA-Z]{2})$", ErrorMessage = "O Email do funcionario está incorreto.")]
        [Display(Name = "Email do funcionário")]
        [StringLength(100, ErrorMessage = "A quantidade de caracteres do Email do funcionário é invalido.")]
        public string EmailFunc { get; set; }

        [Required(ErrorMessage = "O campo RG do funcionário é requerido.")]
        [Display(Name = "RG do funcionário")]
        [RegularExpression(@"^(\d{1,2})(\d{3})(\d{3})(\d{1})$", ErrorMessage = "RG do funcionário invalido")]
        [StringLength(9, ErrorMessage = "A quantidade de caracteres do RG do funcionário é invalido.")]
        public string RgFunc { get; set; }

        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Digite somente letras.")]
        [Display(Name = "Complemento")]
        [StringLength(50, ErrorMessage = "A quantidade de caracteres do Complemento é invalido.")]
        public string Comp { get; set; }

        [Required(ErrorMessage = "O campo Número do edifício é requerido.")]
        [Display(Name = "Número do edifício")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Digite somente números.")]
        public int NumEdif { get; set; }

        public Usuario User { get; set; }

        public string Imagem { get; set; }

        public HttpPostedFileBase ImageUpload { get; set; }



        public void InsertFuncionario(Funcionario funcionario)
        {
            string strQuery = string.Format("CALL sp_InsFuncEndUsu ('{0}','{1}','{2}','{3}','{4}','{5}','{6}','{7}','{8}','{9}','{10}','{11}','{12}','{13}','{14}','{15}','{16}','{17}');", funcionario.Imagem,funcionario.User.UsuarioText, funcionario.User.Senha, funcionario.Endereco.Cidade, funcionario.Endereco.CEP, funcionario.Endereco.Logra, funcionario.Endereco.Bairro, funcionario.Comp, funcionario.NumEdif, funcionario.NomeFunc, funcionario.DatNascFunc.ToString("yyyy-MM-dd"), funcionario.CargoFunc, funcionario.SexoFunc, funcionario.CelFunc.ToString().Replace("(", string.Empty).Replace(")", string.Empty).Replace(" ", string.Empty), funcionario.EmailFunc, funcionario.RgFunc, funcionario.CPFfunc, funcionario.User.TipoAcesso);

            using (db = new ConexaoDB())
            {
                db.ExecutaComando(strQuery);
            }
        }

        public void UpdateFuncionario(Funcionario funcionario)
        {
            string strQuery = string.Format("CALL sp_AtuaFunc('{0}','{1}','{2}','{3}','{4}','{5}','{6}','{7}','{8}','{9}','{10}','{11}','{12}','{13}','{14}','{15}','{16}');", funcionario.IdFunc, funcionario.CPFfunc, funcionario.Endereco.CEP, funcionario.NomeFunc, funcionario.DatNascFunc.ToString("yyyy-MM-dd"), funcionario.CargoFunc, funcionario.SexoFunc, funcionario.CelFunc.ToString().Replace("(", string.Empty).Replace(")", string.Empty).Replace(" ", string.Empty), funcionario.EmailFunc, funcionario.RgFunc, funcionario.Comp, funcionario.NumEdif, funcionario.Endereco.Logra, funcionario.Endereco.Bairro, funcionario.Endereco.Cidade, funcionario.User.UsuarioText, funcionario.User.Senha);


            using (db = new ConexaoDB())
            {
                db.ExecutaComando(strQuery);
            }
        }



        public List<Funcionario> SelecionaFuncionario()
        {
            using (db = new ConexaoDB())
            {

                string StrQuery = string.Format("select * from tbfuncionario;");
                MySqlDataReader registros = db.RetornaRegistro(StrQuery);
                var funcionarioList = new List<Funcionario>();
                var usuTemp = new Usuario
                {
                    IdUsuario = 0,
                    UsuarioText = "",
                    Senha = ""
                };
                while (registros.Read())
                {
                    string idUser = registros["IdUsuario"].ToString();
                    string cpf = registros["CPFfunc"].ToString();
                    string comp = registros["Comp"].ToString();
                    string numedif = registros["NumEdif"].ToString();

                    var FuncionarioTemporario = new Funcionario
                    {
                        IdFunc = int.Parse(registros["IdFunc"].ToString()),
                        Endereco = new Endereco().RetornaPorCEP(registros["CEP"].ToString()),
                        NomeFunc = registros["NomeFunc"].ToString(),
                        CPFfunc = cpf.Equals("") ? "Não há CPF" : registros["CPFfunc"].ToString(),
                        DatNascFunc = DateTime.Parse(registros["DatNascFunc"].ToString()),
                        CargoFunc = registros["CargoFunc"].ToString(),
                        SexoFunc = registros["SexoFunc"].ToString(),
                        CelFunc = Convert.ToInt64(registros["CelFunc"].ToString()),
                        EmailFunc = registros["EmailFunc"].ToString(),
                        RgFunc = registros["RgFunc"].ToString(),
                        Comp = comp.Equals("") ? "Sem complemento" : registros["Comp"].ToString(),
                        NumEdif = numedif.Equals("") ? 0 : int.Parse(registros["NumEdif"].ToString()),
                        Imagem = registros["imagefunc"].ToString(),
                        User = idUser != "" ? new Usuario().RetornaPorIdUsuario(int.Parse(idUser)) : usuTemp
                    };

                    funcionarioList.Add(FuncionarioTemporario);
                }
                //db.Dispose();
                return funcionarioList;
            }

        }


        public Funcionario SelecionaComIdFunc(int IdFunc)
        {
            using (db = new ConexaoDB())
            {
                string StrQuery = string.Format("select * from tbfuncionario where IdFunc = '{0}';", IdFunc);
                MySqlDataReader registros = db.RetornaRegistro(StrQuery);
                Funcionario FuncListando = null;
                while (registros.Read())
                {
                    string user = registros["IdUsuario"].ToString();
                    string cpf = registros["CPFfunc"].ToString();
                    string comp = registros["Comp"].ToString();
                    string numedif = registros["NumEdif"].ToString();
                    FuncListando = new Funcionario
                    {
                        IdFunc = int.Parse(registros["IdFunc"].ToString()),
                        Endereco = new Endereco().RetornaPorCEP(registros["CEP"].ToString()),
                        User = user.Equals("") ? new Usuario() : new Usuario().RetornaPorIdUsuario(int.Parse(registros["IdUsuario"].ToString())),
                        NomeFunc = registros["NomeFunc"].ToString(),
                        CPFfunc = cpf.Equals("") ? "Não há CPF" : registros["CPFfunc"].ToString(),
                        DatNascFunc = DateTime.Parse(registros["DatNascFunc"].ToString()),
                        CargoFunc = registros["CargoFunc"].ToString(),
                        SexoFunc = registros["SexoFunc"].ToString(),
                        CelFunc = Convert.ToInt64(registros["CelFunc"].ToString()),
                        EmailFunc = registros["EmailFunc"].ToString(),
                        RgFunc = registros["RgFunc"].ToString(),

TCC/Controllers/FuncionarioController.cs
using System;
using System.IO;
using System.Web.Mvc;
using TCC.Autorizacoes;
using TCC.Models;

namespace TCC.Controllers
{
    public class FuncionarioController : Controller
    {
        // GET: Funcionario
        public ActionResult Index()
        {
            return View();
        }

        [Autenticacao]
        public ActionResult List(Funcionario funcionario)
        {
            try
            {
                if (int.Parse(Session["NivelAcesso"].ToString()) != 5)
                {
                    return RedirectToAction("ErroAutenticação", "Usuario");
                }
                var funcionarioList = funcionario.SelecionaFuncionario();
                return View(funcionarioList);
            }
            catch
            {
                TempData["msg"] = "<script>alert('Erro ao listar os funcionarios');</script>";
                return View();
            }
        }


        // GET: Funcionario/Details/5
        public ActionResult Details(int IdFunc)
        {
            try
            {
                var funcionario = new Funcionario();
                var objFunc = new Funcionario();
                funcionario = objFunc.SelecionaComIdFunc(IdFunc);
                return View(funcionario);
            }
            catch
            {
                TempData["msg"] = "<script>alert('Erro ao detalhar o funcionario');</script>";
                return View();
            }
        }

        // GET: Funcionario/Create
        [Autenticacao]
        public ActionResult Create()
        {
            if (int.Parse(Session["NivelAcesso"].ToString()) != 5)
            {
                return RedirectToAction("ErroAutenticação", "Usuario");
            }
            return View();
        }

        // POST: Funcionario/Create
        [HttpPost]
        public ActionResult Create(Funcionario funcionario)
        {

            if (ModelState.IsValid)
            {
                var objFunc = new Funcionario();
                string filename = Path.GetFileNameWithoutExtension(funcionario.ImageUpload.FileName);
                string extesion = Path.GetExtension(funcionario.ImageUpload.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + extesion;
                funcionario.Imagem = "~/Imagens/" + filename;
                filename = Path.Combine(Server.MapPath("~/Imagens/"), filename);
                funcionario.ImageUpload.SaveAs(filename);
                objFunc.InsertFuncionario(funcionario);
                return RedirectToAction("List");
            }
            TempData["msg"] = "<script>alert('Erro ao criar o funcionario');</script>";
            return View();
        }

        // GET: Funcionario/Edit/5
        [Autenticacao]
        public ActionResult Edit(int IdFunc)
        {
            if (int.Parse(Session["NivelAcesso"].ToString()) != 5)
            {
                return RedirectToAction("ErroAutenticação", "Usuario");
            }
            var funcionario = new Funcionario();
            var objFunc = new Funcionario();
            funcionario = objFunc.SelecionaComIdFunc(IdFunc);
            return View(funcionario);
        }

        // POST: Funcionario/Edit/5
        [HttpPost]
        public ActionResult Edit(Funcionario funcionario)
        {
            try
            {
                var objFunc = new Funcionario();
                objFunc.UpdateFuncionario(funcionario);
                return RedirectToAction("List");
            }
            catch
            {
                TempData["msg"] = "<script>alert('Erro ao editar o funcionario');</script>";
                return View();
            }
        }

    }
}

TCC/Views/Funcionario/Create.cshtml
@model TCC.Models.Funcionario

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Funcionario", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Funcionario</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CPFfunc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CPFfunc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CPFfunc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco.CEP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco.CEP, new { htmlAttributes = new { @class = "form-control", id = "Cep", name = "Cep" } })
            @Html.ValidationMessageFor(model => model.Endereco.CEP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco.Logra, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco.Logra, new { htmlAttributes = new { @class = "form-control", id = "Logra", name = "Logra" } })
            @Html.ValidationMessageFor(model => model.Endereco.Logra, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco.Bairro, new { htmlAttributes = new { @class = "form-control", id = "Bairro", name = "Bairro" } })
            @Html.ValidationMessageFor(model => model.Endereco.Bairro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco.Cidade, new { htmlAttributes = new { @class = "form-control", id = "Cidade", name = "Cidade" } })
            @Html.ValidationMessageFor(model => model.Endereco.Cidade, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.NomeFunc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NomeFunc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NomeFunc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DatNascFunc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DatNascFunc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DatNascFunc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CargoFunc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CargoFunc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CargoFunc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SexoFunc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SexoFunc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SexoFunc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CelFunc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CelFunc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CelFunc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmailFunc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmailFunc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EmailFunc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RgFunc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RgFunc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RgFunc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Comp, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Comp, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Comp, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumEdif, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumEdif, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumEdif, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.User.UsuarioText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User.UsuarioText, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User.UsuarioText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.User.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User.Senha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User.Senha, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.User.ConfirmaSenha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User.ConfirmaSenha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User.ConfirmaSenha, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.User.TipoAcesso, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User.TipoAcesso, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User.TipoAcesso, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Imagem, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageUpload" required />
            @*@Html.ValidationMessageFor(m => m.Imagem, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}
@Html.Raw(TempData["msg"])
<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {

            function limpa_formulário_cep() {
                // Limpa valores do formulário de cep.
                $("#Logra").val("");
                $("#Bairro").val("");
                $("#Cidade").val("");
                $("#Uf").val("");
            }

            //Quando o campo cep perde o foco.
            $("#Cep").blur(function () {

                //Nova variável "cep" somente com dígitos.
                var cep = $(this).val().replace(/\D/g, '');

                //Verifica se campo cep possui valor informado.
                if (cep != "") {

                    //Expressão regular para validar o CEP.
                    var validacep = /^[0-9]{8}$/;

                    //Valida o formato do CEP.
                    if (validacep.test(cep)) {

                        //Preenche os campos com "..." enquanto consulta webservice.
                        $("#Logra").val("...");
                        $("#Bairro").val("...");
                        $("#Cidade").val("...");
                        $("#Uf").val("...");

                        //Consulta o webservice viacep.com.br/
                        $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {

                            if (!("erro" in dados)) {
                                //Atualiza os campos com os valores da consulta.
                                $("#Logra").val(dados.logradouro);
                                $("#Bairro").val(dados.bairro);
                                $("#Cidade").val(dados.localidade);
                                $("#UF").val(dados.uf);
                            } //end if.
                            else {
                                //CEP pesquisado não foi encontrado.
                                limpa_formulário_cep();
                                alert("CEP não encontrado.");
                            }
                        });
                    } //end if.
                    else {
                        //cep é inválido.
                        limpa_formulário_cep();
                        alert("Formato de CEP inválido.");
                    }
                } //end if.
                else {
                    //cep sem valor, limpa formulário.
                    limpa_formulário_cep();
                }
            });
        });

    </script>
}

TCC/Views/Funcionario/Details.cshtml
@model TCC.Models.Funcionario

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Funcionario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CPFfunc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CPFfunc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.CEP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.CEP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Logra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Logra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Bairro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Bairro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Cidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeFunc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeFunc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatNascFunc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatNascFunc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CargoFunc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CargoFunc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SexoFunc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SexoFunc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CelFunc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CelFunc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailFunc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailFunc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RgFunc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RgFunc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumEdif)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumEdif)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User.TipoAcesso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.TipoAcesso)
        </dd>

    </dl>
</div>
@Html.Raw(TempData["msg"])
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdFunc }) |
    @Html.ActionLink("Back to List", "Index")
</p>